version: '3.6'
services:
  web_gateway:
    image: haproxy:2.6.6-alpine
    container_name: web_gateway
    hostname: web_gateway
    ports:
      - 80:80
      - 9999:9999
    build:
      context: ./haproxy
      dockerfile: Dockerfile
      network: host
    restart: always
    volumes:
      - /var/folders/haproxy:/var/lib/haproxy/:rw
    depends_on:
      - webapp_server_1
      - webapp_server_2
  webapp_server_1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        SERVER_NAME: webapp_server_1
      network: host
    container_name: webapp_server_1
    hostname: webapp_server_1
    ports:
      - 8000:80
      - 8001:81
    restart: on-failure
  webapp_server_2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        SERVER_NAME: webapp_server_2
      network: host
    container_name: webapp_server_2
    hostname: webapp_server_2
    ports:
      - 8010:80
      - 8011:81
    restart: on-failure